server:
  port: 8080

spring:
  application:
    name: chemist-BE
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:18112003_Supabase}
    url: jdbc:postgresql://db.zbxgzvwcfufjyqznkawn.supabase.co:5432/postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        cache:
          use_second_level_cache: false

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=30m

# doc
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
    yaml:
      enabled: true
      path: /api-docs.yaml
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    persist-authorization: true
    display-request-duration: true
    supportedSubmitMethods: get,put,post,delete,options,head,patch,trace
    operationsSorter: alpha
    tagsSorter: alpha
    doc-expansion: none
