server:
  port: 8080

spring:
  application:
    name: chemist-BE
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:chemist}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1232}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        cache:
          use_second_level_cache: false

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=30m

  # Flyway Database Migration Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    sql-migration-suffixes: .sql
    validate-on-migrate: true
    clean-disabled: true
    schemas: public

  # Spring AI Anthropic Configuration - Optimized for stability
  ai:
    mcp:
      client:
        stdio:
          root-change-notification: true
          connections:
            postgres-full-access:
              command: npx
              args:
                - -y
                - mcp-postgres-full-access
                - postgresql://postgres:1232@localhost:5432/chemist
              env:
                TRANSACTION_TIMEOUT_MS: "30000"
                MAX_CONCURRENT_TRANSACTIONS: 5
                PG_STATEMENT_TIMEOUT_MS: "30000"
    anthropic:
      api-key: ${ANTHROPIC_API_KEY:your-anthropic-api-key-here}



# doc
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
    yaml:
      enabled: true
      path: /api-docs.yaml
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    persist-authorization: true
    display-request-duration: true
    supportedSubmitMethods: get,put,post,delete,options,head,patch,trace
    operationsSorter: alpha
    tagsSorter: alpha
    doc-expansion: none

logging:
    level:
        org.springframework.web: DEBUG
#        org.hibernate.SQL: DEBUG
#        org.hibernate.type.descriptor.sql.BasicBinder: TRACE