server:
  port: 8080

spring:
  application:
    name: chemist-BE
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:chemist}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1232}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        cache:
          use_second_level_cache: false

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=30m

  # Flyway Database Migration Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    sql-migration-suffixes: .sql
    validate-on-migrate: true
    clean-disabled: true
    schemas: public

  # Spring AI Anthropic Configuration - Optimized for stability
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          model: claude-3-haiku-20240307       # More stable model
          temperature: 0.7                    # Higher temperature = less processing load
          max-tokens: 2000                    # Reduced to avoid rate limits
          timeout: 30s                       # Add timeout to prevent hanging
        retry:
          max-attempts: 3                     # Add retry mechanism
          backoff:
            initial-interval: 1s
            multiplier: 2
            max-interval: 10s

# doc
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
    yaml:
      enabled: true
      path: /api-docs.yaml
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    persist-authorization: true
    display-request-duration: true
    supportedSubmitMethods: get,put,post,delete,options,head,patch,trace
    operationsSorter: alpha
    tagsSorter: alpha
    doc-expansion: none
