###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "{{username}}",
  "password": "{{password}}"
}

> {%
    client.global.set("access-token", response.body.access_token);
    client.global.set("refresh-token", response.body.refresh_token);
    client.log("Access Token: " + response.body.access_token);
%}

###
GET http://localhost:8080/api/v1/role
Authorization: Bearer {{access-token}}

###
POST http://localhost:8080/api/v1/role
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "name": "ROLE_STUDENT",
  "id": 0
}

###
@id = 7
GET http://localhost:8080/api/v1/role/{{id}}
Authorization: Bearer {{access-token}}

###
PUT http://localhost:8080/api/v1/role/{{id}}
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "name": "ROLE_PARENT",
  "id": 5,
  "create_at": "2025-06-18T12:57:49.333107+07:00",
  "update_at": null,
  "end_at": null
}

###
DELETE http://localhost:8080/api/v1/role/{{id}}
Content-Type: application/json
Authorization: Bearer {{access-token}}